#Analytics Tracking
sg_ga: UA-19247091-8

# Styleguide settings
sg_title: Living Styleguide
sg_version: 1.0
sg_keywords: styleguide, playbook, design, code 
sg_author: Matthew Elsom
sg_description: This Living Styleguide maintains design and code standards for digital tools and services.
sg_language: it
sg_styles: /styleguide/css/styleguide.css
sg_favicon: /styleguide/branding/favicon.ico
# Enable sass to edit Styleguide Template Styles
sass:
  sass_dir: styleguide/_scss #[generate Styleguide styles]
  style: :compressed

# Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Jekyll Serve
port: 4000

# Output settings
title: Style guide del Museo Virtuale di Informatica - DISI Unibo
version: 1.0
keywords: KEYWORDS
author: Andrea De Carolis
description: 
language: it
baseurl: /mistic-sg
destination: _site
sass:
  sass_dir: src/assets/_scss #[generate Product styles]
  style: :compressed

# Permalink
#permalink: /:categories/:title/

# Collections
collections:
  docs: 
    output: true
    
defaults:
  - 
    scope:
      path: "_docs"
    values:
      layout: doc
      type: doc
      maturity: "Proposed"
      scss: "Not Assigned"
  - 
    scope:
      path: "_docs/00-branding"
    values:
      layout: index
      type: "branding"
  - 
    scope:
      path: "_docs/00-get-started"
    values:
      layout: index
      type: "help"
  - 
    scope:
      path: "_docs/02-examples"
    values:
      layout: "example"    
  - 
    scope:
      path: "src/html"
    values:
      layout: pattern
      type: pattern